import { Injectable } from '@nestjs/common';
import { RecordTypeEnum } from '../../../common/enums/record-types.enum';
import { BaseRecordRule, FieldRule } from '../base-record.rule';

@Injectable()
export class SchoolIdentificationRule extends BaseRecordRule {
  protected readonly recordType = RecordTypeEnum.SCHOOL_IDENTIFICATION;

  protected readonly fields: FieldRule[] = [
    // Campo 1: Tipo de registro
    {
      position: 0,
      name: 'tipo_registro',
      required: true,
      minLength: 2,
      maxLength: 2,
      pattern: /^00$/,
      type: 'code',
      description: 'Tipo de registro (sempre 00)',
    },
    // Campo 2: Código de escola - Inep
    {
      position: 1,
      name: 'codigo_inep',
      required: true,
      minLength: 8,
      maxLength: 8,
      pattern: /^\d{8}$/,
      type: 'code',
      description: 'Código INEP da escola (8 dígitos)',
    },
    // Campo 3: Situação de funcionamento
    {
      position: 2,
      name: 'situacao_funcionamento',
      required: true,
      minLength: 1,
      maxLength: 1,
      pattern: /^[123]$/,
      type: 'code',
      description:
        'Situação de funcionamento (1-Em atividade, 2-Paralisada, 3-Extinta)',
    },
    // Campo 4: Data de início do ano letivo
    {
      position: 3,
      name: 'data_inicio_ano_letivo',
      required: false,
      minLength: 10,
      maxLength: 10,
      pattern: /^\d{2}\/\d{2}\/\d{4}$/,
      type: 'date',
      description: 'Data de início do ano letivo (DD/MM/YYYY)',
      conditionalRequired: { field: 'situacao_funcionamento', values: ['1'] },
    },
    // Campo 5: Data de término do ano letivo
    {
      position: 4,
      name: 'data_termino_ano_letivo',
      required: false,
      minLength: 10,
      maxLength: 10,
      pattern: /^\d{2}\/\d{2}\/\d{4}$/,
      type: 'date',
      description: 'Data de término do ano letivo (DD/MM/YYYY)',
      conditionalRequired: { field: 'situacao_funcionamento', values: ['1'] },
    },
    // Campo 6: Nome da escola
    {
      position: 5,
      name: 'nome_escola',
      required: true,
      minLength: 4,
      maxLength: 100,
      pattern: /^[ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ªº– ]+$/,
      type: 'string',
      description: 'Nome da escola',
    },
    // Campo 7: CEP
    {
      position: 6,
      name: 'cep',
      required: true,
      minLength: 8,
      maxLength: 8,
      pattern: /^\d{8}$/,
      type: 'code',
      description: 'CEP da escola (8 dígitos)',
    },
    // Campo 8: Município
    {
      position: 7,
      name: 'municipio',
      required: true,
      minLength: 7,
      maxLength: 7,
      pattern: /^\d{7}$/,
      type: 'code',
      description: 'Código do município (7 dígitos)',
    },
    // Campo 9: Distrito
    {
      position: 8,
      name: 'distrito',
      required: true,
      minLength: 1,
      maxLength: 2,
      type: 'code',
      description: 'Código do distrito',
    },
    // Campo 10: Endereço
    {
      position: 9,
      name: 'endereco',
      required: true,
      minLength: 1,
      maxLength: 100,
      pattern: /^[ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ªº–\/.,  ]+$/,
      type: 'string',
      description: 'Endereço da escola',
    },
    // Campo 11: Número
    {
      position: 10,
      name: 'numero',
      required: false,
      minLength: 0,
      maxLength: 10,
      pattern: /^[ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ªº–\/., ]*$/,
      type: 'string',
      description: 'Número do endereço',
    },
    // Campo 12: Complemento
    {
      position: 11,
      name: 'complemento',
      required: false,
      minLength: 0,
      maxLength: 20,
      pattern: /^[ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ªº–\/., ]*$/,
      type: 'string',
      description: 'Complemento do endereço',
    },
    // Campo 13: Bairro
    {
      position: 12,
      name: 'bairro',
      required: false,
      minLength: 0,
      maxLength: 50,
      pattern: /^[ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ªº–\/., ]*$/,
      type: 'string',
      description: 'Bairro',
    },
    // Campo 14: DDD
    {
      position: 13,
      name: 'ddd',
      required: false,
      minLength: 2,
      maxLength: 2,
      pattern: /^\d{2}$/,
      type: 'code',
      description: 'DDD do telefone',
    },
    // Campo 15: Telefone
    {
      position: 14,
      name: 'telefone',
      required: false,
      minLength: 8,
      maxLength: 9,
      pattern: /^\d{8,9}$/,
      type: 'code',
      description: 'Número do telefone (8 ou 9 dígitos)',
    },
    // Campo 16: Outro telefone de contato
    {
      position: 15,
      name: 'outro_telefone',
      required: false,
      minLength: 8,
      maxLength: 9,
      pattern: /^\d{8,9}$/,
      type: 'code',
      description: 'Outro telefone de contato (8 ou 9 dígitos)',
    },
    // Campo 17: Endereço eletrônico (e-mail) da escola
    {
      position: 16,
      name: 'email',
      required: false,
      minLength: 0,
      maxLength: 100,
      pattern:
        /^[-a-z0-9~!$%^&*_=+}{\'?]+(\.[-a-z0-9~!$%^&*_=+}{\'?]+)*@([a-z0-9_][-a-z0-9_]*(\.[-a-z0-9_]+)*\.(aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro|travel|mobi|[a-z][a-z])|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,5})?$/i,
      type: 'string',
      description: 'Endereço eletrônico (e-mail)',
    },
    // Campo 18: Código do órgão regional de ensino
    {
      position: 17,
      name: 'codigo_orgao_regional',
      required: false,
      minLength: 5,
      maxLength: 5,
      type: 'code',
      description: 'Código do órgão regional de ensino (5 caracteres)',
    },
    // Campo 19: Localização/Zona da escola
    {
      position: 18,
      name: 'localizacao_zona',
      required: true,
      minLength: 1,
      maxLength: 1,
      pattern: /^[12]$/,
      type: 'code',
      description: 'Localização/Zona (1-urbana, 2-rural)',
    },
    // Campo 20: Localização diferenciada da escola
    {
      position: 19,
      name: 'localizacao_diferenciada',
      required: true,
      minLength: 1,
      maxLength: 1,
      pattern: /^[12378]$/,
      type: 'code',
      description:
        'Localização diferenciada (7-Não diferenciada, 1-Assentamento, 2-Terra indígena, 3-Quilombola, 8-Povos tradicionais)',
    },
    // Campo 21: Dependência administrativa
    {
      position: 20,
      name: 'dependencia_administrativa',
      required: true,
      minLength: 1,
      maxLength: 1,
      pattern: /^[1234]$/,
      type: 'code',
      description:
        'Dependência administrativa (1-federal, 2-estadual, 3-municipal, 4-privada)',
    },
    // Campos 22-25: Órgão ao qual a escola pública está vinculada
    {
      position: 21,
      name: 'vinculo_secretaria_educacao',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Secretaria de Educação/MEC (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'dependencia_administrativa',
        values: ['1', '2', '3'],
      },
    },
    {
      position: 22,
      name: 'vinculo_secretaria_seguranca',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Secretaria de Segurança/Forças Armadas (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'dependencia_administrativa',
        values: ['1', '2', '3'],
      },
    },
    {
      position: 23,
      name: 'vinculo_secretaria_saude',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Secretaria da Saúde/MS (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'dependencia_administrativa',
        values: ['1', '2', '3'],
      },
    },
    {
      position: 24,
      name: 'vinculo_outro_orgao',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Outro órgão da administração pública (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'dependencia_administrativa',
        values: ['1', '2', '3'],
      },
    },
    // Campos 26-31: Mantenedora da escola privada
    {
      position: 25,
      name: 'mantenedora_empresa_privada',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Empresa/grupos empresariais/pessoa física (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'situacao_funcionamento',
        values: ['1'],
        andField: 'dependencia_administrativa',
        andValues: ['4'],
      },
    },
    {
      position: 26,
      name: 'mantenedora_sindicatos',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Sindicatos/associações/cooperativas (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'situacao_funcionamento',
        values: ['1'],
        andField: 'dependencia_administrativa',
        andValues: ['4'],
      },
    },
    {
      position: 27,
      name: 'mantenedora_ong',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'ONG nacional ou internacional (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'situacao_funcionamento',
        values: ['1'],
        andField: 'dependencia_administrativa',
        andValues: ['4'],
      },
    },
    {
      position: 28,
      name: 'mantenedora_instituicao_sem_fins',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Instituição sem fins lucrativos (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'situacao_funcionamento',
        values: ['1'],
        andField: 'dependencia_administrativa',
        andValues: ['4'],
      },
    },
    {
      position: 29,
      name: 'mantenedora_sistema_s',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Sistema S (Sesi, Senai, Sesc, outros) (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'situacao_funcionamento',
        values: ['1'],
        andField: 'dependencia_administrativa',
        andValues: ['4'],
      },
    },
    {
      position: 30,
      name: 'mantenedora_oscip',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description:
        'Organização da Sociedade Civil de Interesse Público (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'situacao_funcionamento',
        values: ['1'],
        andField: 'dependencia_administrativa',
        andValues: ['4'],
      },
    },
    // Campo 32: Categoria da escola privada
    {
      position: 31,
      name: 'categoria_escola_privada',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[1234]$/,
      type: 'code',
      description:
        'Categoria da escola privada (1-particular, 2-comunitária, 3-confessional, 4-filantrópica)',
      conditionalRequired: {
        field: 'dependencia_administrativa',
        values: ['4'],
      },
    },
    // Campos 33-35: Poder público responsável pela parceria
    {
      position: 32,
      name: 'parceria_secretaria_estadual',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Parceria com secretaria estadual (0-Não, 1-Sim)',
      conditionalRequired: { field: 'situacao_funcionamento', values: ['1'] },
    },
    {
      position: 33,
      name: 'parceria_secretaria_municipal',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Parceria com secretaria municipal (0-Não, 1-Sim)',
      conditionalRequired: { field: 'situacao_funcionamento', values: ['1'] },
    },
    {
      position: 34,
      name: 'nao_possui_parceria',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Não possui parceria ou convênio (0-Não, 1-Sim)',
      conditionalRequired: { field: 'situacao_funcionamento', values: ['1'] },
    },
    // Campos 36-41: Formas de contratação da parceria estadual
    {
      position: 35,
      name: 'contrato_termo_colaboracao_estadual',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Termo de colaboração estadual (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'parceria_secretaria_estadual',
        values: ['1'],
      },
    },
    {
      position: 36,
      name: 'contrato_termo_fomento_estadual',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Termo de fomento estadual (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'parceria_secretaria_estadual',
        values: ['1'],
      },
    },
    {
      position: 37,
      name: 'contrato_acordo_cooperacao_estadual',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Acordo de cooperação estadual (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'parceria_secretaria_estadual',
        values: ['1'],
      },
    },
    {
      position: 38,
      name: 'contrato_prestacao_servico_estadual',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Contrato de prestação de serviço estadual (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'parceria_secretaria_estadual',
        values: ['1'],
      },
    },
    {
      position: 39,
      name: 'contrato_cooperacao_tecnica_estadual',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description:
        'Termo de cooperação técnica e financeira estadual (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'parceria_secretaria_estadual',
        values: ['1'],
      },
    },
    {
      position: 40,
      name: 'contrato_consorcio_estadual',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description:
        'Contrato de consórcio público/Convênio de cooperação estadual (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'parceria_secretaria_estadual',
        values: ['1'],
      },
    },
    // Campos 42-47: Formas de contratação da parceria municipal
    {
      position: 41,
      name: 'contrato_termo_colaboracao_municipal',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Termo de colaboração municipal (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'parceria_secretaria_municipal',
        values: ['1'],
      },
    },
    {
      position: 42,
      name: 'contrato_termo_fomento_municipal',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Termo de fomento municipal (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'parceria_secretaria_municipal',
        values: ['1'],
      },
    },
    {
      position: 43,
      name: 'contrato_acordo_cooperacao_municipal',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Acordo de cooperação municipal (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'parceria_secretaria_municipal',
        values: ['1'],
      },
    },
    {
      position: 44,
      name: 'contrato_prestacao_servico_municipal',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Contrato de prestação de serviço municipal (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'parceria_secretaria_municipal',
        values: ['1'],
      },
    },
    {
      position: 45,
      name: 'contrato_cooperacao_tecnica_municipal',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description:
        'Termo de cooperação técnica e financeira municipal (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'parceria_secretaria_municipal',
        values: ['1'],
      },
    },
    {
      position: 46,
      name: 'contrato_consorcio_municipal',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description:
        'Contrato de consórcio público/Convênio de cooperação municipal (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'parceria_secretaria_municipal',
        values: ['1'],
      },
    },
    // Campo 48: CNPJ da mantenedora principal
    {
      position: 47,
      name: 'cnpj_mantenedora_principal',
      required: false,
      minLength: 14,
      maxLength: 14,
      pattern: /^\d{14}$/,
      type: 'code',
      description: 'CNPJ da mantenedora principal (14 dígitos)',
    },
    // Campo 49: CNPJ da escola privada
    {
      position: 48,
      name: 'cnpj_escola_privada',
      required: false,
      minLength: 14,
      maxLength: 14,
      pattern: /^\d{14}$/,
      type: 'code',
      description: 'CNPJ da escola privada (14 dígitos)',
    },
    // Campo 50: Regulamentação/autorização
    {
      position: 49,
      name: 'regulamentacao_autorizacao',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[012]$/,
      type: 'code',
      description: 'Regulamentação/autorização (0-Não, 1-Sim, 2-Em tramitação)',
      conditionalRequired: { field: 'situacao_funcionamento', values: ['1'] },
    },
    // Campos 51-53: Esfera administrativa do conselho
    {
      position: 50,
      name: 'esfera_federal',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Esfera federal (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'regulamentacao_autorizacao',
        values: ['1', '2'],
      },
    },
    {
      position: 51,
      name: 'esfera_estadual',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Esfera estadual (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'regulamentacao_autorizacao',
        values: ['1', '2'],
      },
    },
    {
      position: 52,
      name: 'esfera_municipal',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[01]$/,
      type: 'code',
      description: 'Esfera municipal (0-Não, 1-Sim)',
      conditionalRequired: {
        field: 'regulamentacao_autorizacao',
        values: ['1', '2'],
      },
    },
    // Campo 54: Unidade vinculada
    {
      position: 53,
      name: 'unidade_vinculada',
      required: false,
      minLength: 1,
      maxLength: 1,
      pattern: /^[012]$/,
      type: 'code',
      description:
        'Unidade vinculada (0-Sem vínculo, 1-Vinculada a escola básica, 2-Ofertante de educação superior)',
      conditionalRequired: { field: 'situacao_funcionamento', values: ['1'] },
    },
    // Campo 55: Código da escola sede
    {
      position: 54,
      name: 'codigo_escola_sede',
      required: false,
      minLength: 8,
      maxLength: 8,
      pattern: /^\d{8}$/,
      type: 'code',
      description: 'Código da escola sede (8 dígitos)',
      conditionalRequired: { field: 'unidade_vinculada', values: ['1'] },
    },
    // Campo 56: Código da IES
    {
      position: 55,
      name: 'codigo_ies',
      required: false,
      minLength: 1,
      maxLength: 9,
      pattern: /^\d{1,9}$/,
      type: 'code',
      description: 'Código da IES (até 9 dígitos)',
      conditionalRequired: { field: 'unidade_vinculada', values: ['2'] },
    },
  ];
}
